version: '3.8'

services:
  appquiz:
    image: ${DOCKER_REGISTRY-}appquiz
    build:
      context: .
      dockerfile: AppQuiz/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AppQuizDb;Username=postgres;Password=postgres
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - postgres
      - ollama
    networks:
      - app-network

  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AppQuizDb
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    networks:
      - app-network
    environment:
      - OLLAMA_NUM_GPU=100
      - OLLAMA_MAX_LOADED_MODELS=3
      - OLLAMA_GPU_LAYERS=50

volumes:
  postgres:
  ollama-models:

networks:
  app-network:
    driver: bridge