version: '3.8'

services:
  appquiz:
    image: ${DOCKER_REGISTRY-}appquiz
    build:
      context: .
      dockerfile: AppQuiz/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:sqlserver,1433;Database=AppQuizDb;User ID=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - sqlserver
      - ollama

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama

volumes:
  mssql-data:
  ollama-models: